[project]
name = "weaviate-ui"
version = "0.1.0"
description = "FastAPI backend for Weaviate UI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "loguru",
  "packaging>=26.2",
  "python-dotenv",
  "uvicorn",
  "weaviate-client",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
